name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.3.1
  - pip:
      - wandb==0.15.8
      - mlflow==2.6.0
      - hydra-core==1.3.2
      - pyyaml==5.4.1
