name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.3.1
  - pip:
      - mlflow==2.6.0
      - wandb==0.15.8
      - ipython==8.12.3
      - notebook==7.0.6
      - jupyterlab==4.0.9
      - cookiecutter==2.5.0
      - hydra-core==1.3.2
      - matplotlib==3.7.4
      - pandas==2.0.3
